### ISSUE TITLE
Multiple starter-kit based apps results in duplicated components in the sidekick

### ISSUE THREAD

**Issue by blefebvre** [blefebvre/aem-phonegap-starter-kit#12]
Result:

![screenshot 2015-01-19 16 03 31](https://cloud.githubusercontent.com/assets/1048207/5803399/28c36d9a-9fcc-11e4-826e-1e79326032cd.png)

Available components should be limited by path instead of (only) componentGroup.

**Comment by savs** [comment]
We also need to make it clear which components belong to which app. How about adding the brand name and/or app name to the component group for apps, in place of "PhoneGap"?
