### ISSUE TITLE
What's the "btford-angular-phonegap" library used for?

### ISSUE THREAD

**Issue by sblin** [blefebvre/aem-phonegap-starter-kit#37]
aem-phonegap-starter-kit/content-dev/src/main/content/jcr_root/etc/designs/phonegap/brand_name_placeholder/app_name_placeholder/clientlibsall/.content.xml embeds the "btford-angular-phonegap".
What's the use of this library?

**Comment by EsteBusta** [comment]
If i understood good, this is a service (angular.factory) defined to handle the device status, implented to get a promise when it is ready, i mean you get a callback when the device is ready.

**Comment by blefebvre** [comment]
@sblin to quote the author (Brian Ford) [0], "Helper to wrap other PhoneGap APIs to ensure that calls happen after deviceready is fired."

[0] https://github.com/btford/angular-phonegap-ready
