### ISSUE TITLE
Android init missing pge-package.json 

### ISSUE THREAD

**Issue by jollyrubber** [blefebvre/aem-phonegap-starter-kit#38]
I cloned the latest repo, customized and deployed the app. Downloaded the build package from the app dashboard tile, build and tried to run on Android device(s) and emulator. I got a blank white screen after the splash screen. When I hooked up chrome debugger I see this error

Failed to load resource: net::ERR_FILE_NOT_FOUND
 file:///storage/emulated/0/www/libs/mobileapps/components/splash-page/clientlibs.js
[contentInit] determine if initial app copy needs to occur
 clientlibs.js:297
[contentInit] current location: [file:///storage/emulated/0/www/content/phonegap/prototype-mobile-first/en.html]
 clientlibs.js:298
[contentInit] successfully gained access to the file system
 clientlibs.js:362
[contentInit] checking for up-to-date content
 clientlibs.js:416
[contentInit] manifest being read from: [file:///storage/emulated/0/www/pge-package.json]
 clientlibs.js:419
initializeApplication error: [Request to url: [file:///storage/emulated/0/www/pge-package.json]
 resulted in a connection error.]. 
clientlibs.js:1058
Failed to load resource: net::ERR_FILE_NOT_FOUND

**Comment by elafargue** [comment]
Managed to reproduce as well

**Comment by blefebvre** [comment]
@jollyrubber and @elafargue, thanks for reporting. I'm taking a crack at reproducing this issue now.

**Comment by blefebvre** [comment]
I've managed to reproduce the issue and will be applying a fix tomorrow morning. My apologies for the delay getting this resolved.

**Comment by jollyrubber** [comment]
Thanks!

On Fri, Aug 7, 2015 at 12:06 AM, Bruce Lefebvre <notifications@github.com>
wrote:

> I've managed to reproduce the issue and will be applying a fix tomorrow
> morning. My apologies for the delay getting this resolved.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/blefebvre/aem-phonegap-starter-kit/issues/38#issuecomment-128589645>
> .
>



-- 
var signature = {
    name: 'Juan Ayala',
    contact: {
        im: { service: 'google_talk', username: 'juan.ayala.tech@gmail.com'
        phone: { carrier: 'google_voice', number: '(209) 910-3080'
    }
};

**Comment by elafargue** [comment]
... any progress on the issue? Still can't understand exactly what's happening there...

**Comment by blefebvre** [comment]
@elafargue I'm still working away at it. My initial hunch was incorrect since the kitchen-sink repo is now suffering from the same symptoms. I will update as soon as a fix is made.

**Comment by blefebvre** [comment]
@elafargue As a last ditch effort I tried downgrading my PhoneGap CLI to an earlier working version:

`npm install -g phonegap@5.0.0-0.27.0`

Doing so enabled me to get past the missing pge-package.json error. 

Obviously this is not a long term solution, but I hope it unblocks you until I'm able to get things working with the latest CLI.

**Comment by elafargue** [comment]
Any ideas of what's happening? I really can't see why some files are seen
and others seem to be invisible for Cordova...

Ed

**Comment by blefebvre** [comment]
I suspected it might have something to do with the new Cordova whitelist plugin, but adding & configuring the plugin did not get me past the issue. I'll be digging in further to find a real solution next week and looping in one of my colleagues who works on the CLI itself.

**Comment by elafargue** [comment]
ok, thanks! Very intriguing issue...

**Comment by jollyrubber** [comment]
Thank you that is a big help. I notice that the older cli version install
the android 4.0.0 platform, while the new cli install 4.0.2. Perhaps the
problem is in the platform SDK.

On Fri, Aug 7, 2015 at 4:55 PM, Bruce Lefebvre <notifications@github.com>
wrote:

> @elafargue <https://github.com/elafargue> As a last ditch effort I tried
> downgrading my PhoneGap CLI to an earlier working version:
>
> npm install -g phonegap@5.0.0-0.27.0
>
> Doing so enabled me to get past the missing pge-package.json error.
>
> Obviously this is not a long term solution, but I hope it unblocks you
> until I'm able to get things working with the latest CLI.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/blefebvre/aem-phonegap-starter-kit/issues/38#issuecomment-128832363>
> .
>



-- 
var signature = {
    name: 'Juan Ayala',
    contact: {
        im: { service: 'google_talk', username: 'juan.ayala.tech@gmail.com'
        phone: { carrier: 'google_voice', number: '(209) 910-3080'
    }
};
