### ISSUE TITLE
App does not show an icon when run inside the PGE viewer

### ISSUE THREAD

**Issue by blefebvre** [blefebvre/aem-phonegap-starter-kit#9]
To reproduce: connect to an AEM instance which has the starter kit installed.

Result: you will not see an icon listed with the app in PGE viewer.

**Comment by savs** [comment]
Example: 
![screenshot 2015-02-09 11 52 18](https://cloud.githubusercontent.com/assets/294263/6105795/13480e16-b053-11e4-96a9-93d4e7c37e6d.png)

**Comment by savs** [comment]
A workaround: copy-paste /content/phonegap/geometrixx-outdoors/shell/jcr:content/pge-app/app-content/images to /content/phonegap/myappname/shell/jcr:content/pge-app/app-content/images and then copy-paste my icon from http://localhost:4502/assetdetails.html/content/dam/mybrandname/myappname/icon.png over the top of /content/phonegap/myappname/shell/jcr:content/pge-app/app-content/images/www/icon.png

This fixes the icon in the command centre and in the PGE viewer.
